name: Sync to Gitee

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/${{ github.repository_owner }}
          dst: gitee/${{ secrets.GITEE_USERNAME }}
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "${{ github.event.repository.name }}"
          force_update: true
